### PR TITLE
Wind Direction Letters

### PR DESCRIPTION
**Pull request by jwest23**
I added these two changes to my fork of wego so I could get letters instead of the arrow icons for wind direction.  Please add these changes if they're a good fit.

Thanks for wego!

### CODE REVIEW

**Comment by schachmat** [comment]
Heyho @jwest23, I have a few questions regarding your PR:

Why do you think the pad function is less fragile? Imho it is even a regression, since it is not able to trim the provided string, if it is too long. Also it still leaves the problem, that you have to count the escape codes for coloring. If both of these problems can be fixed with a new `pad()` function, I would be happy to apply it.

In which case would you want to fall back to wind direction letters instead of the arrows?

**Comment by jwest23** [comment]
Hello!

"less fragile" is an overstatement since the pad function introduces other problems, for sure.  The pad function only allows for variability in the length of the display string that I couldn't manage with just a slice.  I'll take a look at incorporating both halves of the functionality.

The only reason I wanted this is because one of my terminal setups wasn't displaying the diagonal arrows properly, and instead of fixing the font I figured I'd take the opportunity to learn a little go.  It's only a marginally useful feature, at best.

Thanks again!

**Comment by schachmat** [comment]
Ah, now I see, why you needed the pad function for your patch ('NE' is a character more than the arrow). With a proper pad function as described above it can be used for the other `formatBLA()` functions as well. On truncation it should replace the last character with the '…' Ellipsis character.

For the letters: Please fix your font. The requirements from the README state an 'utf-8 terminal with 256 colors'. Your workaround is well implemented, but not needed and I want to encourage people to use utf-8 if they don't already.

**Comment by jwest23** [comment]
"For the letters: Please fix your font."

I'm going to take this to mean that, in the long run, the main motivation behind the pull request isn't desired.  Therefore, I'm closing this pull request.

**Comment by schachmat** [comment]
I managed to change your `pad()` function to support all the needed features and merged that at least. I left you as the author of the commit, since it was your idea. Thanks for the contribution @jwest23.

**Comment by jwest23** [comment]
Thanks for giving me credit when you did the work.  Glad I could make even
a small contribution.

And thanks again for wego!

**Pull request closed without merging**
