### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by sergiotapia** [comment]
A lot of the commits here are changes from `go fmt`. Try to make the pull request contain only changes that add the Windows support. `go fmt` can be added later on a different pull request.

**Comment by schachmat** [comment]
Actually I already asked a friend of mine (I don't use Windows(c)(r)(tm)) to test the windos relevant changes. There are two important points:

* The coloring library has to support all 256 ANSI colors (which the one from @mattn seems to do).
* It has to work with legacy cmd.exe and also with this new Powershell(c)(r)(tm) thingy.

Also the `-lang` flag is not relevant to this PR.

**Comment by mattn** [comment]
@sergiotapia AFAIK, 90% of go developer uses go fmt. if you don't allow you will get difficult to be given contributions.

**Comment by mattn** [comment]
@schachmat windows cmd.exe (powershell console is just same as cmd.exe) doesn't support 256 color. it can display only 16 (8x2) colors. but go-colorable convert ANSI 256 colors into 16 colors.



> Also the -lang flag is not relevant to this PR.

If you don't allow, please cherry-pick commit.

**Comment by schachmat** [comment]
I squashed the two windows related commits and rebased them onto master.

I'll do the `go fmt` soon too.

Please supply the `-lang` flag in another PR and make sure it is also covered in the config.

@mattn thanks for your contribution.

**Comment by mattn** [comment]
okay, i'll do it.

**Comment by sergiotapia** [comment]
@mattn I know this is merged but I just wanted to clarify. 

What I meant was if your pull request is to add X, the commits should only reflect the code needed to add X. `go fmt` touched on a bunch of other stuff not really related to what the pull request is for, you know what I mean?

Obviously go fmt is a great tool I just thought it was easier for the repo maintainer to see how you added windows support without the other fmt diffs. :smile:

**Pull request closed without merging**
