### PR TITLE
Multi language support

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by schachmat** [comment]
Thanks @mattn.

Please remove the default case when appending to `flags` (The API also works with no language specified) and add it were the default configuration is generated (search for `New York`)

**Comment by mattn** [comment]
done

**Comment by schachmat** [comment]
You still have to add it in the `init()` function. We want a default language of `en` in the automatically generated config there (so users know about this option). We do not want to add another default language parameter to the request url if the user actually removed the language entry from the config (or if it is missing due to an old version of the configfile).

**Comment by mattn** [comment]
right?

**Comment by schachmat** [comment]
Looks good to me @mattn. Unfortunately during merging I noticed that this does not affect the output language. The [API](http://www.worldweatheronline.com/api/docs/multilingual.aspx) supports translations, but the translated weather condition text is returned in a json node depending on the requested language. For example german translations are provided in `lang_de`, but hungarian translations are provided in `lang_hu`. Since this json node does not always have the same name, we cannot just add it to the `cond` struct and a bigger change to the OWM backend is needed to support those translations.

**Comment by mattn** [comment]
Added code to display `lang_XX`

**Comment by kpashka** [comment]
Hi guys. It's not that simple

@mattn You're writing localized value into local variable, leaving `rv` variable unchanged, here - https://github.com/mattn/wego/blob/lang/we.go#L497

I also recommend you to use [objx](github.com/stretchr/objx) package for more elegant MSI manipulations.

@schachmat I guess, you need to store or grab localized values for times of day from somewhere, to make it really multi-lingual:
https://github.com/schachmat/wego/blob/master/we.go#L451

**Comment by schachmat** [comment]
Localizing the time of day is too much imho. Either leave it in english or just print the real time instead („9:00“ instead of „Morning“, etc). I can also imagine this to be user configurable in the front-end part after #1 is resolved.

**Comment by schachmat** [comment]
I just checked the code and the issue pointed out by @kpashka is invalid since all the local variables are references. The code from @mattn works, but does only translate the description from the current weather condition. Since I already rebased and squashed some things around to get a linear history, I will add the translations for the forecast data on my own.

**Comment by schachmat** [comment]
Rebased, squashed, fixed and merged. Thanks for your contribution @mattn.

**Pull request closed without merging**
