### PR TITLE
Responsive rendering, related to #7

### PR DESCRIPTION
**Pull request by bearfrieze**
Implemented responsive rendering as suggested in #7. I tried making rendering more flexible while I was at it.

I had to alter the normal/wide/horizontal view a little to fit into the more flexible rendering model, hope you don't mind.

Equal to or greater than 125 columns:
horizontal

Less than 125 columns:
vertical

### CODE REVIEW

**Comment by markusfisch** [comment]
Until there's a version with responsive rendering implemented, we can use _less_ to make the output horizontally scrollable:

	$ wego | less -RS

Now use the arrow keys to scroll right and left.

**Comment by kutiguy** [comment]
hey i am new to all of this can you create a tut on how to install go and wego plz , it looks very kool

**Comment by gregf** [comment]
@kutiguy To install go read [here](https://golang.org/doc/install#install) after that the wego readme explains the rest.

**Comment by marado** [comment]
+1 to this pull request. Another interesting to have would be a command line option to actually define the format (overriding terminal size detection)

**Comment by schachmat** [comment]
@marado there is already a working split of the backend and frontend in the [issue1 branch](/schachmat/wego/tree/issue1). Note, that It requires Go 1.5 and I also want to clean up the interface between backends and frontends before merging to master. Then this PR can be merged as a separate frontend.

**Comment by kordianbruck** [comment]
This branch seems stale. If anyone wants to pick this back up and rebase it, feel free to do so.

**Pull request closed without merging**
