### PR TITLE
Lookup .wegorc in $WEGORC

### PR DESCRIPTION
**Pull request by difro**
Find .wegorc in $HOME instead of user.Current().HomeDir.
There are cases when these two values are different and
this is more in line with the setup description in README.md

> Copy your API key into the .wegorc file in your $HOME folder

### CODE REVIEW

**Comment by schachmat** [comment]
According to [this](http://windowsitpro.com/systems-management/what-environment-variables-are-available-windows) there is no `$HOME` on windows. `user.Current().HomeDir` still seems to be the most portable solution since golang has to make sure it returns something useful on every supported platform. Can you give me the details where you think `$HOME` and `user.Current().HomeDir` do not match? It is probably better to fix the README for this case.

**Comment by difro** [comment]
At work, we have an environment where we share a userid, but source different bashrc and set different $HOME per user (to get personalized working dirs..)

At first glance,
user.Current().HomeDir seems to fetch homedir from /etc/passwd, ignoring current shell's $HOME.

How about checking for $HOME first, and then when it doesn't exist, check user.Current().HomeDir as backup?  Does this sound ok?

**Comment by schachmat** [comment]
That would basicly be only useful in your setup. I think checking for `$WEGORC` and then falling back to `user.Current().HomeDir` is better, since it allows everyone (even those who don't want to change their `$HOME` to specify another config file). Please amend your commit, instead of creating a new one.

**Comment by difro** [comment]
That sounds reasonable. Amended prev commit.

**Comment by schachmat** [comment]
Merged. Thanks for your contribution @difro.

**Pull request merged**
