### PR TITLE
add night codemap

### PR DESCRIPTION
**Pull request by R11baka**
Add codes for nighth

### CODE REVIEW

**Comment by reportaman** [comment]
@R11baka Any update/plans on this? It would be nice to have this option! Thanks

**Comment by ringsaturn** [comment]
@R11baka 

Hi, can I cherrypick your commit to my fork repo https://github.com/ringsaturn/wego ?

**Comment by R11baka** [comment]
@reportaman Hi! yes!

**Comment by kordianbruck** [comment]
This branch seems stale. If anyone wants to pick this back up and rebase it, feel free to do so.

**Pull request closed without merging**
