### PR TITLE
Replace sun to moon if night time

### PR DESCRIPTION
**Pull request by R11baka**
Resolve https://github.com/schachmat/wego/issues/68

### CODE REVIEW

**Comment by R11baka** [comment]
@schachmat Maybe I send many commits to this PR.

**Comment by schachmat** [comment]
Heyho @R11baka,

Thanks again for your great work! There was already an attempt at this issue in PR #88, but there were still 3 points missing. You managed to tackle the first two already. I'd be happy to merge your PR if you handle the last one as well, adding night-alternative icons for every condition code where a sun is visible currently. It would be a little inconsistent if you have a moon displayed in the `CodeClear` condition at night, but if the next night has the `CodePartlyCloudy` there would still be a sun hiding behind clouds. ;)

**Comment by schachmat** [comment]
Oh and an implementation hint.

Just copy the `codes := map[iface.WeatherCode][]string` map and name the existing one `codesDay` and the new one `codesNight`. You should be able to assign the existing images for cases where there is no sun/moon displayed like `iface.CodeCloudy: codesDay[iface.CodeCloudy],`

**Comment by R11baka** [comment]
@schachmat  If I understand correctly, I shoul replace codeSunny, partly rainly,partly cloudly,partly light rain ?

**Comment by schachmat** [comment]
@R11baka,

There is a sun visible in:
- `CodeHeavyShowers`
- `CodeHeavySnowShowers`
- `CodeLightShowers`
- `CodeLightSleetShowers`
- `CodeLightSnowShowers`
- `CodePartlyCloudy`
- `CodeSunny` (renamed to `CodeClear` in your PR)
- `CodeThunderyShowers`
- `CodeThunderySnowShowers`

They might seem like a lot, but since the sun is clipped equally in most of them, replacing the sun with a moon should not be too hard.

**Comment by R11baka** [comment]
Hi @schachmat . Created new pull request 
https://github.com/schachmat/wego/pull/117

**Pull request closed without merging**
