### PR TITLE
Add verbose info message when launching without .wegorc

### PR DESCRIPTION
**Pull request by zerok**
Right now it is a bit confusing when you just launch wego without reading the README first :-)

### CODE REVIEW

**Comment by schachmat** [comment]
When launching wego without a config file you currently get the backend specific `No API key specified. Setup instructions are in the README.` message, because a default config is created, which lacks a valid API key. This message already mentions the readme.

After your patch, a possible backend that needs no API key setup will still receive this message on the first run. Wego automatically creates a default file so users don't have to go through the hassle to set one up first. Since the only backend currently supported needs an API key, unfortunately users have to touch the config file at least once for now.

Your change just replaces the above message with a more detailed one (assuming the user is smart enough to set up the API key while he is reading through the README). I don't think that level of detail is needed, since the explanation is already in the README.

**Comment by zerok** [comment]
OK, so the placement of the additional information was wrong on my part :) My main issue was though, that mentioning just the word "README" and not telling the user that a sample config file was created or where the README is located (local installation, binary file, ...) doesn't make it much easier to the user :-)

Would amending the backend-specific message with a link to the README and adding a statement in the init function that a sample file was created be fine with you? :)

**Comment by schachmat** [comment]
It's common convention to find the readme file in the directory root of the projects source tree, so I don't like linking to the github page (the project might move to another platform some time).

You can however add something like `No config file found, generating a default one for you right now...`.

**Comment by zerok** [comment]
It is definitely a common convention for the source-distribution path otherwise you can't easily assume that all users have the README file at hand or even know where the source repo is even located online. If you plan to always stick with using go-get as installation approach, then I absolutely agree :-) 

Updated the PR.

**Comment by schachmat** [comment]
The printf should be before the if, not after. ;)

I don't mind distributions to package wego, but I expect a decent packager to include the readme. When I include flags (planned after #1), the usage will of course contain a link to the project host.

**Comment by zerok** [comment]
Awesome :)

Amended.

**Comment by schachmat** [comment]
Merged. Thanks for your contribution @zerok.

**Comment by zerok** [comment]
Thank you 😀

**Pull request merged**
